- title: "Entrepeneurial"
  services: ["Fundraising Video", "Company Culture Video", "Client Testimonials", "Animation", "Product Demo"]

- title: "Events"
  services: ["Promote", "Recap", "Archive"]

- title: "Real Estate"
  services: ["Video Walkthroughs", "Photography", "Agent Profile Videos"]

- title: "Original Content"
  services: ["Music Videos", "Documentaries", "Video Blogs", "Short Films"]